-- TX: createTables
BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS pgs (
	pgId INTEGER PRIMARY KEY,
	path TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS ses (
	seId INTEGER PRIMARY KEY,
	pgId INTEGER NOT NULL,
	stmp DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dox (
	doId INTEGER PRIMARY KEY,
	pgId INTEGER NOT NULL,
	stmp DATETIME DEFAULT CURRENT_TIMESTAMP,
	mdwn TEXT
);

CREATE TABLE IF NOT EXISTS pch (
	pcId INTEGER PRIMARY KEY,
	seId INTEGER NOT NULL,
	doId INTEGER NOT NULL,
	stmp DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lne (
	lnId INTEGER PRIMARY KEY,
	pcId INTEGER NOT NULL,
	line REAL,
	mdwn TEXT
);

END TRANSACTION;
